site_name: FastAPI Decorators
site_url: https://fastapi-decorators.pages.dev
repo_url: https://github.com/Minibrams/fastapi-decorators
repo_name: fastapi-decorators
theme:
  name: material
  custom_dir: docs-overrides
  icon:
    repo: fontawesome/brands/git-alt
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: amber
      accent: amber
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: amber
      accent: amber
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode

  features:
    - content.code.select
    - content.code.annotate
    - toc.follow
    - navigation.tracking

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - toc:
      permalink: true
      toc_depth: 6
      title: On this page

extra:
  analytics:
    provider: custom
