name: Continuous Integration

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.8, 3.9, 3.10, 3.11, 3.12]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python $
        uses: actions/setup-python@v4
        with:
          python-version: $

      - name: Install dependencies
        run: |
          pip install -e .
          pip install -r requirements.txt
          pip install pyright

      - name: Perform static type checking with Pyright
        run: pyright src/

      - name: Run unit tests
        run: python -m unittest discover -s tests/unit_tests

      - name: Run integration tests
        run: python -m unittest discover -s tests/integration_tests
