name: Continuous Integration

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  type-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.7.18"
          enable-cache: true

      - name: Install the project
        run: uv sync --dev

      - name: Perform static type checking with Pyright
        run: uv run pyright .

      - name: Perform static type checking with Mypy
        run: uv run mypy .

  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12", "3.13", "3.14"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.7.18"
          enable-cache: true

      - name: Set up Python ${{ matrix.python-version }}
        run: uv python install ${{ matrix.python-version }}

      - name: Install the project
        run: uv sync --dev

      - name: Perform static type checking with Pyright
        run: uv run pyright fastapi_decorators

      - name: Run tests
        run: uv run pytest .
